spring:
  data:
    mongodb:
      host: 118.25.158.194
      port: 27017
      authentication-database: volunteer_db
      username: david
      password: password
      database: volunteer_db

server:
  port: 8777
  servlet:
    context-path: /volunteer/api